# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-24 23:35
from __future__ import unicode_literals

import core.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import event.models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('start', models.TimeField(default=event.models.round_hours)),
                ('end', models.TimeField(default=event.models.round_two_hours)),
                ('recurrences', core.fields.MoneypatchedRecurrenceField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('party-event', 'Party Event'), ('governing-body-event', 'Governing Body Event'), ('volunteer', 'Volunteering Event'), ('advocacy', 'Advocacy'), ('rally', 'Rally'), ('forum', 'Forum'), ('community', 'Community Meetup'), (None, 'Uncategorized Event')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('organization_type', models.CharField(blank=True, choices=[('democratic', 'Democratic Party Organization'), ('governing-body', 'Governing Body'), ('progressive', 'Progressive Organization'), ('candidate', 'Political Candidate')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', localflavor.us.models.USStateField()),
                ('zipcode', localflavor.us.models.USZipCodeField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('phone', localflavor.us.models.PhoneNumberField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Venue'),
        ),
    ]
